# -*- coding: utf-8 -*-
"""Tugas PAA .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uHLdx-1r25muo9ehLNp56lo3yRKWVgmv

INSERTION SORT
"""

#fungsi insertion sort
def insertion_sort(arr):
    #panjang array
    n = len(arr)
    #perulangan untuk memproses setiap elemen pada bagian tidak terurut
    for i in range(1, n):
        #variabel untuk menentukan nilai saat ini
        key = arr[i]
        j = i - 1
        # Memindahkan elemen yang lebih besar dari key ke posisi setelahnya
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
        # Menampilkan array pada setiap iterasi
        print(f"Iterasi {i}: {arr}")
    return arr

# Contoh penggunaan
arr = [57, 78, 10, 40, 24, 50, 71]
print("Array sebelum diurutkan:", arr)
sorted_arr = insertion_sort(arr)
print("Array setelah diurutkan:", sorted_arr)

"""BUBBLE SORT"""

#fungsi bubble sort
def bubble_sort(arr):
    #panjang array
    n = len(arr)
    #perulangan untuk mengiterasi sebanyak n - 1 kali
    for i in range(n):
        # Flag untuk memeriksa apakah ada perubahan pada setiap iterasi, False berarti tidak ada perubahan
        swapped = False
        #perulangan untuk membandingkan pasangan elemen yang berdekatan
        for j in range(0, n - i - 1):
            # Membandingkan elemen ke j dengan elemen sebelahnya
            if arr[j] > arr[j + 1]:
                # Menukar elemen jika elemen ke j lebih besar
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                # Flag untuk memeriksa apakah ada perubahan pada setiap iterasi, Trua berarti ada perubahan
                swapped = True
        # Jika tidak ada pertukaran pada iterasi ini, array sudah terurut maka perulangan terhenti
        if not swapped:
            break
        # Menampilkan array pada setiap iterasi
        print(f"Iterasi {i + 1}: {arr}")
    return arr

arr = [57, 78, 10, 40, 24, 50, 71]
print("Array sebelum diurutkan:", arr)
sorted_arr = bubble_sort(arr)
print("Array setelah diurutkan:", sorted_arr)